MovieRetail/Models/Movie.cs
using System.ComponentModel.DataAnnotations;

namespace MovieRetail.Models
{
    public class Movie
    {
        
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Title { get; set; } 
        [Required]
        [StringLength(250)]
        public string Info { get; set; }

        [Required]
        public GenreType.GenreType Genre { get; set; }
        [Required]
        [Range(0,10)]
        public float Rating { get; set; }


        public byte[]? ImageData { get; set; } // Byte array to store the image data
        public string? ImageContentType { get; set; } // Mime type of the image (e.g., image/jpeg, image/png)

        [Required]
        [StringLength(100)]
        [Url]
        public string VideoLink { get; set; } // Byte array to store the video data


    }
}

MovieRetail/Controllers/CommentSectionController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc;
using MovieRetail.Areas.Identity.Data;
using MovieRetail.Models;
using Microsoft.Extensions.Caching.Memory;

namespace MovieRetail.Controllers
{
    public class CommentSectionController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly IMemoryCache cache;
        public CommentSectionController(ApplicationDbContext db, IMemoryCache cache)
        {
            this.db = db;
            this.cache = cache;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddComment(MovieViewModel movieViewModel, int movieId)
        {
            // Implement rate limiting here
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var requestCountKey = $"RequestCount_{userId}";

            // Get the current request count from the cache
            int requestCount = cache.GetOrCreate(requestCountKey, entry =>
            {
                // Set the sliding window duration to 1 minute (adjust as needed)
                entry.AbsoluteExpirationRelativeToNow = TimeSpan.FromMinutes(30);
                return 0;
            });

            // Define your rate limit (e.g., max 5 comments per 30 minute)
            int maxRateLimit = 5;

            // Check if the user has exceeded the rate limit
            if (requestCount >= maxRateLimit)
            {
                // Return a response indicating rate limit exceeded (e.g., 429 Too Many Requests)
                return StatusCode(429, "Rate limit exceeded. Please try again later.");
            }

            // Increment the request count for the user
            cache.Set(requestCountKey, requestCount + 1);

    
            if (movieViewModel.commentSection.Title == null || movieViewModel.commentSection.Comment == null)
            {
                return NotFound();
            }

            var currentUser = db.Users.Find(userId);
            if (currentUser == null)
                return BadRequest("user not found?");

            movieViewModel.commentSection.UserId = userId;
            movieViewModel.commentSection.FirstName = currentUser.FirstName;
            movieViewModel.commentSection.LastName = currentUser.LastName;
            movieViewModel.commentSection.MovieId = movieId;
            movieViewModel.commentSection.Time = DateTime.Now;

            db.movieComments.Add(movieViewModel.commentSection);
            db.SaveChanges();

            return RedirectToAction("Details", "Movie", new { id = movieId });
        }


        [HttpPost]
        public IActionResult DeleteComment(int id, int movieId)
        {
            var comment = db.movieComments.FirstOrDefault(c =>c.Id==id);
            if (comment == null)
                return NotFound();

            db.movieComments.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Details", "Movie", new { id = movieId });
        }
    }
}

MovieRetail/Controllers/FavoriteController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using MovieRetail.Areas.Identity.Data;
using MovieRetail.Models;

namespace MovieRetail.Controllers
{
    [Authorize]
    public class FavoriteController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly SortListOfMovies sortList;

        public FavoriteController(ApplicationDbContext db)
        {
            this.db = db;
            sortList=SortListOfMovies.Instance;
            
        }
        public IActionResult Index(GenreType.GenreType type, SortMovies.SortMovies sort)
        {
            ViewData["Sort"] = (int?)sort;
            ViewData["Dropdown"] = (int?)type;

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            List<FavoriteMovie> favoriteMovies = db.favoriteMovies.Where(movie => movie.UserId == userId).ToList();
            List<Movie> tempList = new List<Movie>();

            foreach (var favoriteMovie in favoriteMovies)
            {
                var currentMovie = db.movies.FirstOrDefault(movie => movie.Id == favoriteMovie.MovieId);
                tempList.Add(currentMovie);
            }

            IEnumerable<Movie> dataForMovies = tempList;
            dataForMovies = sortList.SortMovies(dataForMovies, sort);

            if (type != GenreType.GenreType.All)
            {
                dataForMovies = dataForMovies.Where(movie => movie.Genre == type);
            }

            return View(dataForMovies);
        }
        [HttpGet]
        public IActionResult AddOrRemoveFromFavoriteList(int movieId)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var favoriteMovie = db.favoriteMovies.FirstOrDefault(movie => movie.UserId == userId && movie.MovieId==movieId);
            if (favoriteMovie == null)
            {
                //we add it to the database
                db.favoriteMovies.Add(new FavoriteMovie(){MovieId = movieId,UserId = userId});
                db.SaveChanges();
               
                return RedirectToAction("Details", "Movie", new { id = movieId });
            }
            //if we get here, we will remove the film from favorite

            db.favoriteMovies.Remove(favoriteMovie);
            db.SaveChanges();
            return RedirectToAction("Details","Movie", new { id = movieId});
        }

   





    }
}

MovieRetail/Controllers/MovieController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MovieRetail.Areas.Identity.Data;
using MovieRetail.Models;
using MovieRetail.SortMovies;


namespace MovieRetail.Controllers
{
    [Authorize]
    public class MovieController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly SortListOfMovies sortList;
        
        private readonly int maxImageSize;
        public MovieController(ApplicationDbContext db)
        {
            this.db = db;
            sortList = SortListOfMovies.Instance;
            
            maxImageSize =  1024 * 1024;
        }
        
        
        public IActionResult Index(GenreType.GenreType type, SortMovies.SortMovies sort)
        {
            IEnumerable<Movie> movies = db.movies;
           
            movies = sortList.SortMovies(movies,sort);
            ViewData["Sort"] = (int?)sort;
            ViewData["Dropdown"] = (int?)type;

            if (type != GenreType.GenreType.All)
            {
                movies = movies.Where(movie => movie.Genre == type);
            }

            return View(movies);
        }

        //GET
        [HttpGet]
        [Authorize(Roles="Admin")]
        public IActionResult CreateMovie()
        {
           
            return View();
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult CreateMovie(Movie movie, IFormFile ImageData)
        {

            if (!ModelState.IsValid)
                return View();

            if (!(ImageData.ContentType == "image/jpeg" || ImageData.ContentType == "image/png"))
            {
                ModelState.AddModelError("ImageData", "Please upload a PNG or JPEG image.");
                return View();
            }
            if (ImageData.Length > maxImageSize) 
            {
                ModelState.AddModelError("ImageData", "The image size must be less than 1 MB.");
                return View(movie);
            }


            movie.ImageData = IFormFileToByteArray(ImageData);
          
            movie.ImageContentType=ImageData.ContentType;
          

            db.movies.Add(movie);
            db.SaveChanges();
            

            return RedirectToAction("Index", "Movie");
        }


        //GET
        [HttpGet]
        public IActionResult Details(int? id)
        {
            ViewData["id"] = id;

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);//To check if it is on favorite list
            var favoriteMovie = db.favoriteMovies.FirstOrDefault(movie => movie.UserId == userId && movie.MovieId==id);

            

            if(favoriteMovie != null)
                ViewData["favoriteMovie"] = "red";
            else
            {
                ViewData["favoriteMovie"] = "yellow";
            }

            IEnumerable<Movie> movies = db.movies;
            IEnumerable<MovieComments> comments = db.movieComments.Where(comment=>comment.MovieId==id);
            MovieComments commentSection = new MovieComments();

            MovieViewModel movieViewModel = new MovieViewModel()
            {
                movies = movies,
                allComments = comments,
                commentSection = commentSection
            };
            return View(movieViewModel);
        }
        [HttpGet]
        public IActionResult SearchDetails(string title)
        {
            Movie currentMovie = db.movies.FirstOrDefault(options => options.Title.Contains(title));

            if (currentMovie == null)
                return NotFound();
            return RedirectToAction("Details", new { id = currentMovie.Id });
        }

        //GET
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int? id)
        {
            if (id == null || id < 0)
                return NotFound();
            Movie movie = db.movies.FirstOrDefault(options => options.Id == id);
            if (movie == null)
                return NotFound();
            return View(movie);
        }
        //POST

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(Movie movie,IFormFile ImageData)
        {
            if (!ModelState.IsValid)
                return View();

            if (!(ImageData.ContentType == "image/jpeg" || ImageData.ContentType == "image/png"))
            {
                ModelState.AddModelError("ImageData", "Please upload a PNG or JPEG image.");
                return View();
            }
            if (ImageData.Length > maxImageSize) 
            {
                ModelState.AddModelError("ImageData", "The image size must be less than 1 MB.");
                return View(movie);
            }


            movie.ImageData = IFormFileToByteArray(ImageData);

            movie.ImageContentType = ImageData.ContentType;


            db.movies.Update(movie);
            db.SaveChanges();


            return RedirectToAction("Details", "Movie", new { id = movie.Id });
        }  //GET
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int? id)
        {
            if (id == null || id < 0)
                return NotFound();
            Movie movie = db.movies.FirstOrDefault(options => options.Id == id);
            if (movie == null)
                return NotFound();
            return View(movie);
        }
        //POST

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(Movie movie)
        {
            

            List<FavoriteMovie> favoriteMovies = db.favoriteMovies.Where(favoriteMovie => favoriteMovie.MovieId == movie.Id).ToList();
            db.movies.Remove(movie);

            foreach (var favoriteMovie in favoriteMovies)
            {
                db.favoriteMovies.Remove(favoriteMovie);
            }

            db.SaveChanges();


            return RedirectToAction("Index", "Movie");
        }





        public byte[] IFormFileToByteArray(IFormFile imageIn)
        {
            using (var memoryStream = new MemoryStream())
            {
                imageIn.CopyTo(memoryStream);
                return memoryStream.ToArray();
            }
        }
    }
}

MovieRetail/Views/Movie/CreateMovie.cshtml
@using MovieRetail.GenreType
@model Movie

@{
    ViewData["Title"] = "Create";
   
}
<br/>
<h1>Create Movie</h1>

<br/>

<div class="row">
    <div class="col md-4">
        <form asp-action="CreateMovie" asp-controller="Movie" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="All"></div>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control"/>
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <br/>
            <div class="form-group">
                <label asp-for="Info" class="control-label"></label>
                <input asp-for="Info" class="form-control"/>
                <span asp-validation-for="Info" class="text-danger"></span>
            </div>
            <br/>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <select asp-for="Genre" asp-items="Html.GetEnumSelectList<GenreType>()" class="form-control">
                    <option value="">Select Genre</option>
                </select>
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <br/>
            <div class="form-group">
                <label asp-for="Rating"></label>
                <input asp-for="Rating" type="number" step="any" class="form-control-number"/>
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <br/>
            <div class="form-group">
                <label asp-for="ImageData">Upload Image:</label>
                <input asp-for="ImageData" type="file" class="form-control-file"/>
                <span asp-validation-for="ImageData" class="text-danger"></span>
            </div>
            <br/>
            <div class="form-group">
                <label asp-for="VideoLink">Upload Video:</label>
                <input asp-for="VideoLink" type="url" class="form-control"/>
                <span asp-validation-for="VideoLink" class="text-danger"></span>
            </div>

            <br/>
            <br/>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

MovieRetail/Views/Movie/Delete.cshtml
@using MovieRetail.GenreType
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model Movie

@{
    ViewData["Title"] = "Create";
   
}
<br/>
<h1>Create Movie</h1>

<br/>

<div class="row">
    <div class="col md-4">
        <form asp-action="Delete" asp-controller="Movie" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="All"></div>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" disabled="disabled"/>
               
            </div>
            <br/>
            <div class="form-group">
                <label asp-for="Info" class="control-label"></label>
                <input asp-for="Info" class="form-control" disabled="disabled"/>
              
            </div>
            <br/>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <select asp-for="Genre" asp-items="Html.GetEnumSelectList<GenreType>()" class="form-control" disabled="disabled">
                    <option value="">Select Genre</option>
                </select>
            
            </div>
            <br/>
            <div class="form-group">
                <label asp-for="Rating"></label>
                <input asp-for="Rating" type="number" step="any" class="form-control-number" disabled="disabled"/>
               
            </div>
            <br/>
  
            <div class="form-group">
                <label asp-for="VideoLink">Upload Video:</label>
                <input asp-for="VideoLink" type="url" class="form-control" disabled="disabled"/>
        
            </div>

            <br/>
            <br/>
            <div class="form-group">
                <input type="submit" value="Delete" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

MovieRetail/Views/Movie/Details.cshtml
@using MovieRetail.Areas.Identity.Data
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using System.Security.Claims

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@model MovieViewModel

@{
    ViewData["Title"] = "Details";
}
@if (Model == null)
{
    <br/>
    <div width="50%" style="text-align: center;">
        <h1>Movie not available</h1>
    </div>
}
else
{
    <div>
        
        @{

            int id = int.Parse(ViewData["id"].ToString());
            Movie currentMovie = Model.movies.FirstOrDefault(movie =>movie.Id==id);
            IEnumerable<Movie> recommendedMovies = Model.movies.Where(movie => movie.Genre == currentMovie.Genre && movie!=currentMovie);

            Random random = new Random();
            recommendedMovies = recommendedMovies.OrderBy(movie => random.Next());
            
        }
    </div>
    <div>
        @{
            byte[] imageBytes = currentMovie.ImageData;
            string base64Image = Convert.ToBase64String(imageBytes);
            string dataUrl = $"data:{currentMovie.ImageContentType};base64,{base64Image}";
        }
    </div>
  

<br/>
    <div width="50%" style="text-align: center;">
        <h1>@currentMovie.Title</h1>
    </div>

    <div class="w-40 btn-group" role="group">
        @if (ViewData["favoriteMovie"].Equals("yellow"))
        {
            <a asp-controller="Favorite" asp-action="AddOrRemoveFromFavoriteList" asp-route-movieId="@currentMovie.Id" class="btn btn-warning mx-2 "><i class="bi bi-star-fill"></i></a>
        }
        else
        {
            <a asp-controller="Favorite" asp-action="AddOrRemoveFromFavoriteList" asp-route-movieId="@currentMovie.Id" class="btn btn-danger mx-2 "><i class="bi bi-x-circle"></i></a>
        }
       
    </div>
    
    <div style="text-align: center;">
        @{
            int linkId = currentMovie.VideoLink.IndexOf('=');
            string s = currentMovie.VideoLink.Substring(linkId + 1);
            string final = $"https://www.youtube.com/embed/{s}";
        }
        <iframe width="900" height="500" src=@final>
        </iframe>
    </div>
    
    <br/>
    <h1>Rating : @currentMovie.Rating/10.0 <i class="bi bi-star-fill"></i></h1>

    <br/>
    <h1>Genre: @currentMovie.Genre</h1>

    <br/>
    <h1>Info <i class="bi bi-info-circle-fill"></i></h1>

    <p>@currentMovie.Info</p>
    <br/>

    <h1>You may also want to see:</h1>
    
    <div class="d-flex">
        @{
            int index = 0;
            foreach (var movie in recommendedMovies)
            {
                if(index>=3)
                    break;
                <div class="p-2" style="width: 33.33%;">
                    @{
                        byte[] tempImageBytes = movie.ImageData;
                        string tempBase64Image = Convert.ToBase64String(tempImageBytes);
                        string tempDataUrl = $"data:{movie.ImageContentType};base64,{tempBase64Image}";
                    }
                    <a class="nav-link" asp-controller="Movie" asp-action="Details" asp-route-id="@movie.Id">
                        <img src="@tempDataUrl" class="img-fluid" style="object-fit: contain;" />
                    </a>
                </div>
                index++;
            }
        }
    </div>


    @if (SignInManager.IsSignedIn(User) && await UserManager.IsInRoleAsync(UserManager.GetUserAsync(User).Result,"admin"))
    {
        <div class="w-40 btn-group" role="group">
            <a asp-controller="Movie" asp-action="Edit" asp-route-id="@currentMovie.Id" class="btn btn-primary mx-2 "><i class="bi bi-pencil-square"></i></a>
            <a asp-controller="Movie" asp-action="Delete" asp-route-id="@currentMovie.Id" class="btn btn-danger mx-2 "><i class="bi bi-trash3-fill"></i></a>
        </div>
    }
    <br/>
    <br/>
    <h1>Comments</h1>   
    <br/>

    <form asp-controller="CommentSection" asp-action="AddComment" asp-route-movieId="@id" method="post">
        <!-- Other form elements... -->

        <div class="form-group">
            <label asp-for="@Model.commentSection.Title" class="control-label">Title</label>
            <input asp-for="@Model.commentSection.Title" required="true" class="form-control"/>
            <span asp-validation-for="@Model.commentSection.Title" class="text-danger"></span>
        </div>
        <br/>
        <div class="form-group">
            <label asp-for="@Model.commentSection.Comment" class="control-label">Comment</label>
            <textarea asp-for="@Model.commentSection.Comment" required="true" class="form-control"> </textarea>
            <span asp-validation-for="@Model.commentSection.Comment" class="text-danger"></span>
        </div>
        <!-- Other form elements... -->
        <br/>
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
 
    <br/>
    <br/>
    <div class="comment-section">
        @{
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            foreach (var comment in Model.allComments)
            {
                <div class="comment">
                    <p><small>@comment.Time</small></p>
                    <strong>@comment.FirstName @comment.LastName</strong>
                    <h5>@comment.Title</h5>
                    <textarea class="form-control bg-light" disabled>@comment.Comment</textarea>

                    @if ((SignInManager.IsSignedIn(User) && await UserManager.IsInRoleAsync(UserManager.GetUserAsync(User).Result, "admin")) || comment.UserId == userId)
                    {
                        <br/>
                        <div class="w-40 btn-group" role="group">
                            <form asp-controller="CommentSection" asp-action="DeleteComment" asp-route-id="@comment.Id" asp-route-movieId="@comment.MovieId" method="post">
                                <button type="submit" class="btn btn-danger"><i class="bi bi-trash3-fill"></i></button>
                            </form>
                        </div>
                    }

                </div>
                <hr/>
            }
        }
    </div>
    
}

MovieRetail/Views/Movie/Edit.cshtml
@using MovieRetail.GenreType
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model Movie

@{
    ViewData["Title"] = "Create";
   
}
<br/>
<h1>Create Movie</h1>

<br/>

<div class="row">
    <div class="col md-4">
        <form asp-action="Edit" asp-controller="Movie" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="All"></div>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control"/>
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <br/>
            <div class="form-group">
                <label asp-for="Info" class="control-label"></label>
                <input asp-for="Info" class="form-control"/>
                <span asp-validation-for="Info" class="text-danger"></span>
            </div>
            <br/>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <select asp-for="Genre" asp-items="Html.GetEnumSelectList<GenreType>()" class="form-control">
                    <option value="">Select Genre</option>
                </select>
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <br/>
            <div class="form-group">
                <label asp-for="Rating"></label>
                <input asp-for="Rating" type="number" step="any" class="form-control-number"/>
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <br/>
            <div class="form-group">
                <label asp-for="ImageData">Upload Image:</label>
                <input asp-for="ImageData" type="file" class="form-control-file"/>
                <span asp-validation-for="ImageData" class="text-danger"></span>
            </div>
            <br/>
            <div class="form-group">
                <label asp-for="VideoLink">Upload Video:</label>
                <input asp-for="VideoLink" type="url" class="form-control"/>
                <span asp-validation-for="VideoLink" class="text-danger"></span>
            </div>

            <br/>
            <br/>
            <div class="form-group">
                <input type="submit" value="Edit" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

MovieRetail/Views/Movie/Index.cshtml
@using MovieRetail.GenreType
@using MovieRetail.SortMovies
@using Microsoft.OpenApi.Extensions
@using System.ComponentModel.DataAnnotations
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model IEnumerable<Movie> 
@{
    ViewData["Title"] = "Index";
   
}
<br/>
<div class="btn-group" role="group" aria-label="Button group with nested dropdown">
    <button type="button" class="btn btn-primary">@((GenreType)ViewData["Dropdown"])</button>
    <div class="btn-group" role="group">
        <button id="btnGroupDrop1" type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
        <div class="dropdown-menu" aria-labelledby="btnGroupDrop1" style="">
            @{
                GenreType[] genreType = (GenreType[])Enum.GetValues(typeof(GenreType));
                    
                foreach (var type in genreType)
                {
                    <a class="dropdown-item" asp-controller="Movie" asp-action="Index" asp-route-type="@type" asp-route-sort="@((SortMovies)ViewData["Sort"])">@type.ToString()</a>
                }

            }
    
        </div>
    </div>
   
</div>
@{
    var sortType = (SortMovies)ViewData["Sort"];
    var currentName = sortType.GetType().GetField(sortType.ToString())
        .GetCustomAttributes(typeof(DisplayAttribute), false)
        .OfType<DisplayAttribute>()
        .FirstOrDefault()?.Name ?? sortType.ToString();
}

<div class="btn-group" role="group" aria-label="Button group with nested dropdown">
    <button type="button" class="btn btn-primary">@currentName</button>
    <div class="btn-group" role="group">
        <button id="btnGroupDrop1" type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
        <div class="dropdown-menu" aria-labelledby="btnGroupDrop1" style="">
            @{
                var sortTypes = Enum.GetValues(typeof(SortMovies)).Cast<SortMovies>();
                    
                foreach (var type in sortTypes)
                {
                    var displayName = type.GetType().GetField(type.ToString())
                        .GetCustomAttributes(typeof(DisplayAttribute), false)
                        .OfType<DisplayAttribute>()
                        .FirstOrDefault()?.Name ?? type.ToString();
                    <a class="dropdown-item" asp-controller="Movie" asp-action="Index" asp-route-type="@((GenreType)ViewData["Dropdown"])" asp-route-sort="@type">@displayName</a>
                }

            }

        </div>
    </div>
   
</div>

@if (!Model.Any())
{
    <h2 class="text-primary">There are no movies available.</h2>
}
else
{   <br/>

    <div class="container p-0">
        <div class="row pt-2">
        </div>
    </div>

  


    

    <table class="table table-bordered table-striped" style="width:50%">
        
        <tbody>

        @if (Model != null && Model.Count() >= 2)
        {
            <table>
                @for (int i = 0; i < Model.Count(); i += 2)
                {
                    <tr>
                        @for (int j = i; j < i + 2 && j < Model.Count(); j++)
                        {
                            <td width="50%" style="text-align: center;">
                                <h3>@Model.ElementAt(j).Title</h3>
                            </td>
                        }
                    </tr>
                    <tr>
                            @for (int j = i; j < i + 2 && j < Model.Count(); j++)
                            {
                                <td width="50%">
                                    @{
                                        byte[] imageBytes = Model.ElementAt(j).ImageData;
                                        string base64Image = Convert.ToBase64String(imageBytes);
                                        string dataUrl = $"data:{Model.ElementAt(j).ImageContentType};base64,{base64Image}";
                                    }
                                    <a class="nav-link" asp-controller="Movie" asp-action="Details" asp-route-id="@Model.ElementAt(j).Id">
                                        <img src="@dataUrl" width="100%" style="object-fit: contain;" />
                                    </a>
                                </td>
                            }
                        </tr>
                       
                }
            </table>
        }
        else if (Model!=null && Model.Count() == 1)
        {

            <tr>
                <td width="50%" style="text-align: center;">
                    <h3>@Model.ElementAt(0).Title</h3>
                </td>
            </tr>
            <tr>
                <td width="50%">
                    @{
                        byte[] imageBytes = Model.ElementAt(0).ImageData;
                        string base64Image = Convert.ToBase64String(imageBytes);
                        string dataUrl = $"data:{Model.ElementAt(0).ImageContentType};base64,{base64Image}";
                    }
                    <a class="nav-link" asp-controller="Movie" asp-action="Details" asp-route-id="@Model.ElementAt(0).Id">
                        <img src="@dataUrl" width="100%" style="object-fit: contain;" />
                    </a>
                </td>
            </tr>
        }
        </tbody>

    </table>
    
}
@section Scripts
{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}